import { expect, test, type Page, type TestInfo } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type DiagnosticsSnapshot = {
  schemaVersion: 1; frameCount: number;
  frameMs: { p50:number;p95:number;p99:number;max:number;over50Percent:number };
  longTasks: { over250:number;over1000:number;maxMs:number };
  webgl: { lost:number;restored:number;fallback:number };
  runtimeErrors:number; unhandledRejections:number; chaptersVisited:string[]; [key:string]:unknown;
};
type DiagnosticsWindow = Window & { __CDJ_DIAGNOSTICS__?: { snapshot(): DiagnosticsSnapshot }; __CDJ_TELEMETRY_OVERRIDE__?: Record<string,string|undefined> };
const externalHosts=/(?:plausible\.io|google-analytics\.com|sentry\.io)$/;

async function instantChapter(page:Page,id:string,progress=.5){await page.evaluate(({chapterId,localProgress})=>{const section=document.querySelector<HTMLElement>(`[data-chapter-id="${chapterId}"]`);if(!section)throw new Error(`Missing chapter ${chapterId}`);const top=section.offsetTop+section.offsetHeight*localProgress-window.innerHeight*.5;document.documentElement.style.scrollBehavior='auto';window.scrollTo({top:Math.max(0,top),behavior:'instant'});},{chapterId:id,localProgress:progress});await expect(page.locator('.experience-shell')).toHaveAttribute('data-active-chapter',id);await page.waitForTimeout(90);}
async function completeJourney(page:Page){const ids=await page.locator('[data-chapter-id]').evaluateAll(nodes=>nodes.map(node=>(node as HTMLElement).dataset.chapterId).filter((id):id is string=>Boolean(id)));expect(ids).toHaveLength(10);for(const id of ids)await instantChapter(page,id,.55);return ids;}
async function writeDiagnostics(page:Page,testInfo:TestInfo){const snapshot=await page.evaluate(()=>{const bridge=(window as DiagnosticsWindow).__CDJ_DIAGNOSTICS__;if(!bridge)throw new Error('Missing localhost diagnostics bridge');return bridge.snapshot();});const dir=join(process.cwd(),'v2.1-diagnostics',testInfo.project.name);mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'performance-diagnostics.json'),`${JSON.stringify({...snapshot,project:testInfo.project.name},null,2)}\n`,'utf8');return snapshot;}

test('normal deterministic journey stays local-only and writes diagnostics',async({page},testInfo)=>{const pageErrors:string[]=[],externalRequests:string[]=[];page.on('pageerror',e=>pageErrors.push(e.name));page.on('request',request=>{try{if(externalHosts.test(new URL(request.url()).hostname))externalRequests.push(request.url());}catch{/* browser internals */}});await page.goto('/');await expect(page.getByRole('main')).toBeVisible();await expect(page.getByRole('button',{name:/turn sound on/i})).toHaveAttribute('aria-pressed','false');const ids=await completeJourney(page);const snapshot=await writeDiagnostics(page,testInfo);expect(snapshot.schemaVersion).toBe(1);expect(snapshot.frameCount).toBeGreaterThan(0);expect(snapshot.runtimeErrors).toBe(0);expect(snapshot.unhandledRejections).toBe(0);expect(snapshot.webgl.lost).toBe(0);expect(snapshot.chaptersVisited).toEqual(ids);expect(pageErrors).toEqual([]);expect(externalRequests).toEqual([]);});

test('DNT and Global Privacy Control suppress Plausible and GA4 even when localhost flags enable them',async({page},testInfo)=>{test.skip(testInfo.project.name!=='chromium-desktop');const requests:string[]=[];page.on('request',r=>{const host=new URL(r.url()).hostname;if(host==='plausible.io'||host.endsWith('google-analytics.com'))requests.push(r.url());});await page.addInitScript(()=>{Object.defineProperty(navigator,'doNotTrack',{configurable:true,get:()=> '1'});Object.defineProperty(navigator,'globalPrivacyControl',{configurable:true,get:()=>true});(window as DiagnosticsWindow).__CDJ_TELEMETRY_OVERRIDE__={VITE_TELEMETRY_MODE:'external',VITE_PLAUSIBLE_ENABLED:'true',VITE_PLAUSIBLE_DOMAIN:'stars.example',VITE_GA4_ENABLED:'true',VITE_GA4_MEASUREMENT_ID:'G-TEST123'};});await page.goto('/');await instantChapter(page,'collapse');await instantChapter(page,'main-sequence');expect(requests).toEqual([]);});

test('startup without WebGL preserves the complete semantic narrative',async({page},testInfo)=>{test.skip(testInfo.project.name!=='chromium-desktop');await page.addInitScript(()=>{HTMLCanvasElement.prototype.getContext=function getContext(){return null;} as typeof HTMLCanvasElement.prototype.getContext;});await page.goto('/');await expect(page.locator('[data-chapter-id]')).toHaveCount(10);await expect(page.getByRole('status')).toContainText('without WebGL');await expect(page.getByRole('main')).toBeVisible();});

test('one synthetic context restore is bounded and a second loss falls back without losing chapter progress',async({page},testInfo)=>{test.skip(testInfo.project.name!=='chromium-desktop');await page.goto('/');await instantChapter(page,'main-sequence');const shell=page.locator('.experience-shell');const canvas=page.locator('.experience-canvas canvas');await expect(canvas).toBeVisible();await canvas.evaluate(node=>node.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await expect(shell).toHaveAttribute('data-webgl-recovery','restoring');await canvas.evaluate(node=>node.dispatchEvent(new Event('webglcontextrestored')));await expect(shell).toHaveAttribute('data-webgl-recovery','healthy');await expect(shell).toHaveAttribute('data-active-chapter','main-sequence');const remounted=page.locator('.experience-canvas canvas');await expect(remounted).toBeVisible();await remounted.evaluate(node=>node.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await expect(shell).toHaveAttribute('data-webgl-recovery','fallback');await expect(shell).toHaveAttribute('data-active-chapter','main-sequence');await expect(page.getByRole('status')).toContainText('without WebGL');});
