import test from 'node:test';
import assert from 'node:assert/strict';
import { createDiagnosticsAccumulator, evaluateDiagnostics } from '../../src/observability/diagnostics.ts';
import type { ObservabilityEvent } from '../../src/observability/types.ts';
const event=(name:ObservabilityEvent['name'],context:ObservabilityEvent['context']={},at=0):ObservabilityEvent=>({name,context,at});

test('diagnostics computes bounded frame percentiles and long-task aggregates',()=>{const now=0;const d=createDiagnosticsAccumulator(()=>now);for(const ms of [10,20,30,40,60,70,80,90,100,110])d.recordFrame(ms);d.recordLongTask(275);d.recordLongTask(1200);const s=d.snapshot();assert.equal(s.frameCount,10);assert.equal(s.frameMs.p50,60);assert.equal(s.frameMs.p95,110);assert.equal(s.frameMs.p99,110);assert.equal(s.frameMs.max,110);assert.equal(s.frameMs.over50Percent,60);assert.deepEqual(s.longTasks,{over250:2,over1000:1,maxMs:1200});});
test('diagnostics aggregates lifecycle events without retaining duplicate chapter ids',()=>{const d=createDiagnosticsAccumulator(()=>0);d.recordEvent(event('chapter.enter',{chapterId:'overture'}));d.recordEvent(event('chapter.enter',{chapterId:'overture'}));d.recordEvent(event('chapter.enter',{chapterId:'collapse'}));d.recordEvent(event('runtime.error',{errorClass:'TypeError'}));d.recordEvent(event('runtime.unhandled-rejection',{errorClass:'Error'}));d.recordEvent(event('webgl.context-lost'));d.recordEvent(event('webgl.context-restored'));d.recordEvent(event('webgl.fallback'));d.recordEvent(event('audio.enabled'));d.recordEvent(event('audio.suspended'));const s=d.snapshot();assert.deepEqual(s.chaptersVisited,['overture','collapse']);assert.equal(s.runtimeErrors,1);assert.equal(s.unhandledRejections,1);assert.deepEqual(s.webgl,{lost:1,restored:1,fallback:1});assert.equal(s.audioEvents,2);});
test('quality transition timing and heap growth stay deterministic',()=>{let now=100;const d=createDiagnosticsAccumulator(()=>now);now=200;d.recordQualityTransition(0,1,now);now=500;d.recordQualityTransition(1,2,now);d.setHeapBaseline(1000);d.setHeapCurrent(5000);now=900;const s=d.snapshot();assert.equal(s.qualityTransitions,2);assert.deepEqual(s.timeAtAdaptiveLevelMs,[100,300,400,0]);assert.equal(s.adaptiveLevel,2);assert.equal(s.heapGrowthBytes,4000);});
test('budget evaluator separates stable failures from noisy performance warnings',()=>{const d=createDiagnosticsAccumulator(()=>0);for(let i=0;i<100;i++)d.recordFrame(i<90?20:80);d.recordLongTask(300);d.recordLongTask(350);d.recordLongTask(400);const r=evaluateDiagnostics(d.snapshot(),'chromium-desktop');assert.equal(r.status,'warn');assert.ok(r.warnings.some(m=>m.includes('p95')));assert.ok(r.warnings.some(m=>m.includes('frames >50ms')));assert.deepEqual(r.failures,[]);});
test('runtime errors context loss extreme long tasks and abnormal heap growth hard-fail',()=>{const d=createDiagnosticsAccumulator(()=>0);d.recordEvent(event('runtime.error',{errorClass:'TypeError'}));d.recordEvent(event('runtime.unhandled-rejection',{errorClass:'Error'}));d.recordEvent(event('webgl.context-lost'));d.recordLongTask(1200);d.setHeapBaseline(0);d.setHeapCurrent(129*1024*1024);const r=evaluateDiagnostics(d.snapshot(),'chromium-desktop');assert.equal(r.status,'fail');assert.ok(r.failures.length>=5);});
test('mobile level 3 at snapshot is reported as a warning rather than a flaky hard failure',()=>{let now=0;const d=createDiagnosticsAccumulator(()=>now);now=100;d.recordQualityTransition(0,3,now);const r=evaluateDiagnostics(d.snapshot(1000),'chromium-mobile');assert.equal(r.status,'warn');assert.ok(r.warnings.some(m=>m.includes('adaptive level 3')));});
