import type { Chapter } from './types.ts';

const authored = (note: string) => [{ kind: 'authored' as const, note }];

export const chapters: readonly Chapter[] = [
  {
    id: 'overture',
    eyebrow: 'A stellar lifetime',
    title: 'Ten billion years begin in the dark.',
    body: 'Long before a star has a name, a cold cloud of gas drifts through the galaxy. Gravity only needs one uneven patch to begin changing everything.',
    interactionCue: 'Move through the dust. Click to send a pressure wave.',
    clockLabel: 'Before the clock',
    scene: 'dust',
    scrollLength: 1.2,
    sourceProvenance: authored('Original clean-room narrative based on standard stellar-evolution concepts.'),
  },
  {
    id: 'cold-cloud',
    eyebrow: 'T − 1,000,000 years',
    title: 'A cloud starts to remember its center.',
    body: 'Hydrogen and helium cool enough for gravity to win small arguments. Knots form. The densest knot pulls harder, gathering more material and deepening the well.',
    interactionCue: 'Your pointer becomes a small local pull.',
    clockLabel: '−1 million years',
    scene: 'dust',
    scrollLength: 1.1,
    sourceProvenance: authored('Original explanatory text.'),
  },
  {
    id: 'collapse',
    eyebrow: 'Gravitational collapse',
    title: 'Falling inward makes the cloud spin faster.',
    body: 'As the protostar contracts, infalling gas trades distance for speed. Compression raises the core temperature while a disk-like flow organizes around the center.',
    interactionCue: 'Sweep across the cloud to bend nearby trajectories.',
    clockLabel: 'Approaching ignition',
    scene: 'collapse',
    scrollLength: 1.35,
    sourceProvenance: authored('Original explanatory text.'),
  },
  {
    id: 'ignition',
    eyebrow: 'T = 0',
    title: 'The core ignites.',
    body: 'Pressure and temperature climb until hydrogen nuclei can fuse. Energy now streams outward from the core, pushing back against gravity and announcing a new star.',
    interactionCue: 'Pass through the flash as fusion stabilizes the core.',
    clockLabel: 'Fusion begins',
    scene: 'fusion',
    scrollLength: 0.95,
    sourceProvenance: authored('Original explanatory text.'),
  },
  {
    id: 'main-sequence',
    eyebrow: 'The long middle',
    title: 'For billions of years, two forces negotiate.',
    body: 'Gravity presses inward. Fusion-powered pressure pushes outward. Their balance can persist for most of a Sun-like star’s life while planets circle through a changing field of light.',
    interactionCue: 'Move near the star to push the surrounding dust outward.',
    clockLabel: '+5 billion years',
    scene: 'main-sequence',
    scrollLength: 1.7,
    sourceProvenance: authored('Original explanatory text.'),
  },
  {
    id: 'red-giant',
    eyebrow: 'Hydrogen runs low',
    title: 'The envelope expands into a red giant.',
    body: 'When the core’s hydrogen fuel is depleted, the internal balance shifts. Shell burning and a hotter contracting core drive the outer layers to swell far beyond their earlier size.',
    interactionCue: 'Watch the inner system disappear inside the expanding envelope.',
    clockLabel: '+10 billion years',
    scene: 'red-giant',
    scrollLength: 1.35,
    sourceProvenance: authored('Original explanatory text.'),
  },
  {
    id: 'shedding',
    eyebrow: 'The outer layers loosen',
    title: 'The star gives its atmosphere back to space.',
    body: 'Pulses and stellar winds release glowing shells. Enriched gas travels outward, building a planetary nebula that will eventually mix into future clouds and future stars.',
    interactionCue: 'Follow each shell as it drifts away from the remnant.',
    clockLabel: 'A brief luminous aftermath',
    scene: 'nebula',
    scrollLength: 1.35,
    sourceProvenance: authored('Original explanatory text.'),
  },
  {
    id: 'white-dwarf',
    eyebrow: 'The remnant',
    title: 'A white dwarf remains.',
    body: 'The exposed core is compact, hot, and no longer powered by sustained fusion. It radiates stored heat while the surrounding nebula thins into the interstellar medium.',
    interactionCue: 'Motion quiets as the remnant cools.',
    clockLabel: 'Cooling for ages',
    scene: 'white-dwarf',
    scrollLength: 1.2,
    sourceProvenance: authored('Original explanatory text.'),
  },
  {
    id: 'elsewhere',
    eyebrow: 'Elsewhere in the galaxy',
    title: 'More massive stars can end differently.',
    body: 'A sufficiently massive stellar core can collapse beyond the white-dwarf path. In the most extreme outcome, a black hole forms while nearby material can heat into a brilliant accretion flow.',
    interactionCue: 'Disturb the accretion disk with your pointer.',
    clockLabel: 'An alternate ending',
    scene: 'black-hole',
    scrollLength: 1.35,
    sourceProvenance: authored('Original explanatory text.'),
  },
  {
    id: 'epilogue',
    eyebrow: 'Epilogue',
    title: 'Stars end. Their material keeps going.',
    body: 'Every ending changes the chemical and gravitational landscape around it. The next cloud begins with atoms, momentum, and history inherited from stars that came before.',
    interactionCue: 'Scroll back through the lifetime or leave the remnant drifting.',
    clockLabel: 'The cycle continues',
    scene: 'dust',
    scrollLength: 1,
    sourceProvenance: authored('Original closing text.'),
  },
] as const;
